language: node_js

node_js:
  - lts/*

script:
  - pnpm run lint
  - pnpm run build

cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7.0.0
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm install
