version: 2.1

orbs:
  node: circleci/node@5.2.0
  codecov: codecov/codecov@3.3.0

executors:
  base:
    docker:
      - image: cimg/base:stable
  node:
    docker:
      - image: "cimg/node:20.12.1"
  go:
    docker:
      - image: cimg/go:1.22.2

parameters:
  trigger-app:
    type: boolean
    default: false
  run-them-all:
    type: boolean
    default: false

jobs:
  ## Backend
  test_app:
    executor: go
    working_directory: ~/go/src/github.com/ArtalkJS/Artalk
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: "Print the Go version"
          command: >
            go version
      - restore_cache:
          keys:
            - go-mod-1.22.2-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-1.22.2-{{ checksum "go.sum" }}
          paths:
            - "~/go/pkg/mod"
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-reports
            gotestsum --junitfile /tmp/test-reports/unit-tests.xml -- -coverprofile=/tmp/test-reports/coverage.out ./...
      - store_test_results:
          path: /tmp/test-reports
      - codecov/upload:
          flags: go
          file: /tmp/test-reports/coverage.out

  all_projects:
    executor: base
    steps:
      - run:
          command: |
            echo "all"

workflows:
  build-app:
    when:
      or:
        - << pipeline.parameters.trigger-app >>
        - << pipeline.parameters.run-them-all >>
    jobs:
      - test_app

  build-shared-other:
    when: << pipeline.parameters.run-them-all >>
    jobs:
      - all_projects
