# https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# this allows you to use CircleCI's dynamic configuration
# https://circleci.com/docs/2.0/dynamic-config/
setup: true

# the path-filtering orb is required to continue a pipeline based on
# https://circleci.com/developer/orbs/orb/circleci/path-filtering
orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          mapping: |
            (cmd|internal|server|pkg|test|conf)/.*  trigger-app true
            main.go|go.mod|go.sum  trigger-app true
          base-revision: master  # git branch name
          config-path: .circleci/conditional_config.yml
          filters:
            branches:
              ignore:
                - gh-pages
                - /release\/.+/
                - nightly
